import unittest
import pet

class TestPetExceptions(unittest.TestCase):

    def setUp(self):
        pass

    def test_something(self):
        self.fail("implement me")
